### ISSUE TITLE
app-location should fire events!

### ISSUE THREAD

**Issue by gaurav21r** [PolymerElements/app-route#108]
### Description

From the docs, `app-location` is an element that provides synchronization between the browser location bar and the state of an app.

A WebComponent like an HTMLelement, should have properties (DOM Props or Attributes), methods and events.

### Expected outcome

There should be an event like `onRouteChange` which I can `addEventListener` to and get the parsed route details in `e`.

### Actual outcome

There is already a private function called `_routeChanged` which is supposedly called when the URL changes (as per my understanding of the docs).

It should be easy enough to call a `this.fire` inside the function so that an event is fired. If the core members agree I can submit a PR.

**Comment by rictic** [comment]
I agree that it should! Fortunately, it does! Here's a demo: https://jsbin.com/wosecuwesa/edit?html,output

All polymer elements fire `${propertyName}-changed` events when their properties are updated. App-location also fires the `location-changed` event on window when it updates window.location, and it listens for this event as well, so that it's easy to interop with other libraries that also do pushState/replaceState.

The `location-changed` event could be better documented, I'll send over a PR for this now.
