### ISSUE TITLE
data and tail not reset in app-route's __resetProperties call

### ISSUE THREAD

**Issue by ppalladino** [PolymerElements/app-route#137]
### Description

app-route's 'data' and 'tail' properties are not reset in the __resetProperties call. If a route path is updated shouldn't the data and tail be reevaluated as well? Looks like their reset was commented out in the current version. What was the reason for commenting this out?

### Expected outcome

Data and tail should be revaluated on reset
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by zinkkrysty** [comment]
Looks like it's commented in the tests as well, without any particular reason:
https://github.com/PolymerElements/app-route/blob/master/test/app-route.html#L131

I would expect it to be the normal behavior to reset the data, otherwise any binding to both the data and the active property will trigger twice - making it impossible to change the views.

**Comment by ppalladino** [comment]
I am sure there was a good reason to comment this out, I am just curious why? And maybe if I can help fix it. @zinkkrysty Yes you are right, I was having issues with bindings to data having old values when they should be blank.

**Comment by rictic** [comment]
As you've surmised we do have a justification for this. The principle behind this is that an inactive app-route should be as inert as possible, and not issue updates to its properties. We do this because inactive app-routes are typically mapped into hidden parts of the dom (because other dom is now visible, e.g. through iron-pages). It's unexpected and wasteful for the invisible parts of the dom to be updating, changing, and being reevaluated.

Of course it's also unexpected for your app-routes to not be always up to date as well. It can be a tricky tradeoff. Feedback welcome!

**Comment by ppalladino** [comment]
Ah! Understood. Any suggestions on how to handle this case:

1. 3 nested app-routes A, B and C (primary, secondary and tertiary nav). Each is fed their parent's tail.
1. Initial path /a1/b1/c1 matches patterns on each app-route so 
   - A.data.foo = a1
   - B.data.foo = b1
   - C.data.foo = c1
1. we navigate to /a1/b2 (notice we left out c*) and the updated data is:
   - A.data.foo = a1
   - B.data.foo = b2
   - C.data.foo = c1 <- old value persists because __resetProperties does not clear data
1. we navigate back to /a1/b1 (notice we left out c*) and the updated data is:
   - A.data.foo = a1
   - B.data.foo = b1
   - C.data.foo = c1 <- tertiary nav is wrongly set to c1 when it should be null!!

**Comment by zinkkrysty** [comment]
@ppalladino I solved this situation by creating a listener for both the data change and the active property like so:

```html
<app-route route="{{mainRoute}}" pattern="/:foo" data="{{aData}} active="{{aIsActive}}" tail="{{aTail}}></app-route>
<app-route route="{{aTail}}" pattern="/:foo" data="{{bData}} active="{{bIsActive}}" tail="{{bTail}}"></app-route>
<app-route route="{{cTail}}" pattern="/:foo" data="{{cData}} active="{{bIsActive}}"></app-route>
```

```js
listeners: [
  'routeDataChanged(aData.foo, bData.foo, cData.foo, aIsActive, bIsActive, cIsActive)'
],

routeDataChanged: function(aFoo, bFoo, cFoo, aIsActive, bIsActive, cIsActive) {
  // Check if aIsActive, bIsActive, cIsActive and perform different actions (change page)
}
```

The problem I have with this solution is that for some reason the `routeDataChanged` is triggered many times (more than it's necessary) when a child route becomes inactive. It might be a bug, where the change notification gets fired, even if there is no change in the value of these properties.

Another solution would be to bind each of these `aFoo, aIsActive`, `bFoo, bIsActive`, `cFoo, cIsActive` pairs to a computed property so that one reflects the actual data value (and you can set it yourself to `null` if the route is inactive.

**Comment by ppalladino** [comment]
@zinkkrysty Yup. This is the approach I took as well. I guess my main issue is that the view component needs to handle state and logic to determine if C.data.foo value is outdated data that has not been reset or accurate data from a new incoming path. I would like to see app-route handle that, as that it is its job to handle route state. Would it not be desirable to keep view components as stateless as possible and have that state managed by the router? Just my opinion. Thanks for help!

**Comment by bedeoverend** [comment]
This one tripped me up as well, took quite awhile to figure out what was going on, perhaps just needs more obvious documentation around what will happen when it fails to match a pattern? 

Also what about if you could define optional params in the pattern e.g. `/:resource?`. That way the route knows it should update `data` in the case when it's not matched, so `data.resource` will be `''` empty on `/`. Something tells me though that that would have a lot of implications I'm not considering.

**Comment by pdesjardins90** [comment]
For me it's just weird that being at /section/:id, and hitting back to /section doesn't trigger an update, I had to fork the repo just to decomment those 2 lines to workaround that

**Comment by anoblet** [comment]
This issue applies to my project as well. I have this configuration:

/:page then /:id

In my page i use the id to decide whether or not to show a list, or a single item. When I navigate to /page id remains null. Then to /page/0 and id changes to 0. Then back to /page and id still remains 0. I'm currently using an observer to reset the data if route.path = ''. This doesn't seem to be incredibly efficient though. Any new on this?

**Comment by chrismclarke** [comment]
same issue, keen to know if there has been any response to this
